### PR TITLE
ci: update python-package workflow to use trusted publishing

### LINKED ISSUE #39: Use trusted publishling for pypi release
**Is your feature request related to a problem? Please describe.**
From https://docs.pypi.org/trusted-publishers/:

> This confers significant usability and security advantages when compared to PyPI's traditional authentication methods:
>
> 
> Usability: with trusted publishing, users no longer need to manually create API tokens on PyPI and copy-paste them into their CI provider. The only manual step is configuring the publisher on PyPI.
>  Security: PyPI's normal API tokens are long-lived, meaning that an attacker who compromises a package's release token can use it until its legitimate user notices and manually revokes it. Trusted publishing avoids this problem because the tokens minted expire automatically.

**Describe the solution you'd like**
I would like to propose to use a trusted publishing implementation for pypi releases. See [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by korikuzma**
close #39

Additional changes:
* Update action versions + python version used

### CODE REVIEW

**Review by jsstevenson — DISMISSED** [review]

**Comment by korikuzma** [comment]
In biocommons maintainers 8/26 meeting, we decided GitHub environments are not needed at this time.

**Comment by reece** [comment]
@korikuzma Have you figured out how to test this action? I tried two tags and a commit, but no luck. I'm going to merge and try.

**Review by reece — APPROVED** [review]
Thank you @korikuzma !

**Comment by reece** [comment]
I updated the tag expressions after merge to accommodate alpha, beta, rc, dev, and post tags.

**Comment by reece** [comment]
And it worked... 

image

**Pull request merged**
